# Generated by Django 6.0.3 on 2026-03-22 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


PROFILE_MODEL = "accounts.profile"


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_seed_profile_page_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorshipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to=PROFILE_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to=PROFILE_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_matches",
                        to=PROFILE_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_matches",
                        to=PROFILE_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match",
                        to="accounts.mentorshiprequest",
                    ),
                ),
            ],
            options={
                "db_table": "matches",
                "ordering": ["-request__created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mentorshiprequest",
            index=models.Index(
                fields=["mentor", "status"],
                name="mentorship__mentor__e850bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mentorshiprequest",
            index=models.Index(
                fields=["mentee", "status"],
                name="mentorship__mentee__2dd85d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorshiprequest",
            constraint=models.CheckConstraint(
                condition=~models.Q(mentor=models.F("mentee")),
                name="mentorship_request_mentor_not_mentee",
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorshiprequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("mentor", "mentee"),
                name="uniq_pending_request_per_mentor_mentee",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["mentor", "is_active"],
                name="matches_mentor__f1729a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["mentee", "is_active"],
                name="matches_mentee__dea405_idx",
            ),
        ),
    ]
