# Generated by Django 6.0.3 on 2026-03-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_state_transfer_domain_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("GUEST", "Guest"), ("USER", "User"), ("ADMIN", "Admin")],
                default="USER",
                max_length=16,
            ),
        ),
    ]
