# Generated by Django 6.0.3 on 2026-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_usage_mode',
            field=models.CharField(blank=True, choices=[('MENTEE', 'Mentee'), ('MENTOR', 'Mentor')], max_length=16),
        ),
    ]
