# Generated by Django 6.0.3 on 2026-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_grandfather_existing_users_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[("LOCAL", "Local"), ("GOOGLE", "Google")], default="LOCAL", max_length=16
            ),
        ),
    ]
