# Generated by Django 6.0.3 on 2026-05-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_user_app_usage_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="app_usage_mode",
            field=models.CharField(
                blank=True,
                choices=[("MENTEE", "Mentee"), ("MENTOR", "Mentor"), ("ADMIN", "Admin")],
                max_length=16,
                null=True,
            ),
        ),
    ]
