# Generated by Django 6.0.3 on 2026-05-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_user_app_usage_mode"),
        ("messaging", "0003_message_original_filename"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("submitted_by", "reported_user"), name="unique_report_per_user_pair"
            ),
        ),
    ]
