# Generated by Django 6.0.3 on 2026-04-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("profiles", "0010_remove_expertise_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actor_notifications",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="extra_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="resource_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="resource_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_mentorship_request", "New Mentorship Request"),
                    ("mentorship_request_rejected", "Mentorship Request Rejected"),
                    ("new_match", "New Match"),
                    ("slot_booked", "Slot Booked"),
                    ("session_canceled", "Session Canceled"),
                    ("session_rescheduled", "Session Rescheduled"),
                    ("match_deactivated", "Match Deactivated"),
                    ("new_message", "New Message"),
                    ("new_feedback_available", "New Feedback Available"),
                ],
                max_length=50,
            ),
        ),
    ]
