# Generated by Django 6.0.3 on 2026-04-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_action_url_notification_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_mentorship_request', 'New Mentorship Request'), ('mentorship_request_rejected', 'Mentorship Request Rejected'), ('new_match', 'New Match'), ('slot_booked', 'Slot Booked'), ('session_canceled', 'Session Canceled'), ('session_rescheduled', 'Session Rescheduled'), ('match_deactivated', 'Match Deactivated'), ('new_message', 'New Message'), ('new_feedback_available', 'New Feedback Available'), ('tag_new_member', 'Tag New Member'), ('tag_description_updated', 'Tag Description Updated'), ('tag_deleted', 'Tag Deleted'), ('tag_matches_interest', 'Tag Matches Interest')], max_length=50),
        ),
    ]
