name: Task
description: Create a new task for the project
title: "[TASK]: "
labels: []
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Brief description of the task
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain the reasoning and purpose behind this task.
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Define the boundaries and extent of this task.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide detailed information about this task.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Reviewed by team
        - label: Solution implemented
        - label: Tested and verified
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional information or considerations.
