# Generated by Django 6.0.3 on 2026-03-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0001_state_transfer"),
        ("profiles", "0002_profile_username"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name="mentorshiprequest",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("mentor", models.F("mentee")), _negated=True),
                        name="mentorship_request_mentor_not_mentee",
                    ),
                ),
            ],
        ),
    ]
