# Generated by Django 6.0.3 on 2026-04-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0002_mentorshiprequest_mentorship_request_mentor_not_mentee"),
        ("profiles", "0008_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshiprequest",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mentorship_requests",
                to="profiles.availabilityslot",
            ),
        ),
    ]
