# Generated by Django 6.0.3 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0003_mentorshiprequest_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshiprequest",
            name="initial_session_end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorshiprequest",
            name="initial_session_start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
