# Generated by Django 6.0.3

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0005_refresh_seed_with_realistic_mock_data"),
        ("profiles", "0009_profile_average_rating_review_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="mentorship.match",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_feedbacks",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(
                fields=["match", "submitted_by"],
                name="uniq_feedback_per_match_participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.CheckConstraint(
                condition=models.Q(rating__gte=1) & models.Q(rating__lte=5),
                name="feedback_rating_between_1_and_5",
            ),
        ),
    ]
