# Generated by Django 6.0.3

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0006_feedback"),
        ("profiles", "0009_profile_average_rating_review_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_start_at_utc", models.DateTimeField()),
                ("scheduled_end_at_utc", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("CANCELED", "Canceled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                (
                    "canceled_by_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MENTOR", "Mentor"),
                            ("MENTEE", "Mentee"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("cancel_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_sessions",
                        to="mentorship.match",
                    ),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_meeting_sessions",
                        to="profiles.profile",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_meeting_sessions",
                        to="profiles.profile",
                    ),
                ),
                (
                    "source_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_sessions",
                        to="profiles.availabilityslot",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_sessions",
                "ordering": ["-scheduled_start_at_utc", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="meetingsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scheduled_end_at_utc__gt", models.F("scheduled_start_at_utc"))
                ),
                name="meeting_session_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("mentor", models.F("mentee")), _negated=True),
                name="meeting_session_mentor_not_mentee",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingsession",
            index=models.Index(
                fields=["mentor", "scheduled_start_at_utc"],
                name="meeting_ses_mentor__73f9cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingsession",
            index=models.Index(
                fields=["mentee", "scheduled_start_at_utc"],
                name="meeting_ses_mentee__62bf31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingsession",
            index=models.Index(
                fields=["status", "scheduled_start_at_utc"],
                name="meeting_ses_status_34a9fd_idx",
            ),
        ),
    ]
