# Generated by Django 6.0.3

from django.db import migrations
from django.utils import timezone


def _resolve_session_window(request_obj):
    """Resolve session times and source slot id from request state."""
    slot = request_obj.slot
    if slot is not None:
        return slot.start_at, slot.end_at, slot.id

    return (
        request_obj.initial_session_start_at,
        request_obj.initial_session_end_at,
        None,
    )


def _resolve_session_status(*, source_slot_id, start_at, end_at, now):
    """Map inferred session timing to a canonical status value."""
    if source_slot_id is None and start_at >= now:
        return "CANCELED"
    if end_at <= now:
        return "COMPLETED"
    return "SCHEDULED"


def backfill_meeting_sessions(apps, schema_editor):
    """Populate MeetingSession rows from accepted requests and match/session snapshots."""
    match_model = apps.get_model("mentorship", "Match")
    meeting_session_model = apps.get_model("mentorship", "MeetingSession")

    now = timezone.now()

    for match in match_model.objects.select_related("request", "request__slot").iterator():
        if meeting_session_model.objects.filter(match_id=match.id).exists():
            continue

        request_obj = getattr(match, "request", None)
        if request_obj is None or request_obj.status != "ACCEPTED":
            continue

        start_at, end_at, source_slot_id = _resolve_session_window(request_obj)

        if start_at is None or end_at is None:
            continue

        session_status = _resolve_session_status(
            source_slot_id=source_slot_id,
            start_at=start_at,
            end_at=end_at,
            now=now,
        )

        meeting_session_model.objects.create(
            match_id=match.id,
            mentor_id=match.mentor_id,
            mentee_id=match.mentee_id,
            source_slot_id=source_slot_id,
            scheduled_start_at_utc=start_at,
            scheduled_end_at_utc=end_at,
            status=session_status,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0007_meetingsession"),
    ]

    operations = [
        migrations.RunPython(backfill_meeting_sessions, migrations.RunPython.noop),
    ]
