# Generated by Django 6.0.3 on 2026-04-20 16:22

from django.db import migrations
from django.db.migrations.operations.models import RenameIndex


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0008_backfill_meeting_sessions"),
    ]

    operations = [
        RenameIndex(
            model_name="meetingsession",
            new_name="meeting_ses_mentor__62e580_idx",
            old_name="meeting_ses_mentor__73f9cd_idx",
        ),
        RenameIndex(
            model_name="meetingsession",
            new_name="meeting_ses_mentee__67ce09_idx",
            old_name="meeting_ses_mentee__62bf31_idx",
        ),
        RenameIndex(
            model_name="meetingsession",
            new_name="meeting_ses_status_ba878f_idx",
            old_name="meeting_ses_status_34a9fd_idx",
        ),
    ]
