# Generated by Django 6.0.3 on 2026-05-09 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mentorship",
            "0009_rename_meeting_ses_mentor__73f9cd_idx_meeting_ses_mentor__62e580_idx_and_more",
        ),
        ("profiles", "0019_merge_0018_conflicts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("scheduled_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("max_participants", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_workshops",
                        to="profiles.profile",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_workshops",
                        to="profiles.communitytag",
                    ),
                ),
            ],
            options={
                "db_table": "workshops",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("show_on_profile", models.BooleanField(default=False)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshop_participations",
                        to="profiles.profile",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="mentorship.workshop",
                    ),
                ),
            ],
            options={
                "db_table": "workshop_participants",
                "ordering": ["joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(fields=["community", "status"], name="workshops_communi_04b597_idx"),
        ),
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(fields=["author", "status"], name="workshops_author__2a721c_idx"),
        ),
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(fields=["scheduled_at"], name="workshops_schedul_dd4c2c_idx"),
        ),
        migrations.AddConstraint(
            model_name="workshop",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gt", models.F("scheduled_at"))),
                name="workshop_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="workshopparticipant",
            index=models.Index(fields=["workshop"], name="workshop_pa_worksho_fad948_idx"),
        ),
        migrations.AddIndex(
            model_name="workshopparticipant",
            index=models.Index(fields=["participant"], name="workshop_pa_partici_bca81a_idx"),
        ),
        migrations.AddConstraint(
            model_name="workshopparticipant",
            constraint=models.UniqueConstraint(
                fields=("workshop", "participant"), name="uniq_workshop_participant"
            ),
        ),
    ]
