# Generated by Django 6.0.3 on 2026-05-06 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0016_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('scheduled_start_at_utc', models.DateTimeField()),
                ('scheduled_end_at_utc', models.DateTimeField()),
                ('min_participants', models.PositiveSmallIntegerField(default=1)),
                ('max_participants', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_workshops', to='profiles.profile')),
            ],
            options={
                'db_table': 'workshops',
                'ordering': ['-scheduled_start_at_utc', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_size', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='CONFIRMED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_participations', to='profiles.profile')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='workshops.workshop')),
            ],
            options={
                'db_table': 'workshop_participations',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['mentor', 'scheduled_start_at_utc'], name='workshops_mentor__fc0856_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['status', 'scheduled_start_at_utc'], name='workshops_status_633610_idx'),
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_end_at_utc__gt', models.F('scheduled_start_at_utc'))), name='workshop_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.CheckConstraint(condition=models.Q(('min_participants__gte', 1)), name='workshop_min_participants_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.CheckConstraint(condition=models.Q(('max_participants__gte', models.F('min_participants'))), name='workshop_max_participants_gte_min'),
        ),
        migrations.AddIndex(
            model_name='workshopparticipation',
            index=models.Index(fields=['workshop', 'status'], name='workshop_pa_worksho_7e61e1_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopparticipation',
            index=models.Index(fields=['mentee', 'status'], name='workshop_pa_mentee__8f9052_idx'),
        ),
        migrations.AddConstraint(
            model_name='workshopparticipation',
            constraint=models.UniqueConstraint(fields=('workshop', 'mentee'), name='uniq_participation_per_workshop_mentee'),
        ),
        migrations.AddConstraint(
            model_name='workshopparticipation',
            constraint=models.CheckConstraint(condition=models.Q(('group_size__gte', 1)), name='workshop_participation_group_size_gte_1'),
        ),
    ]
