# Generated by Django 6.0.3 on 2026-05-01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "mentorship",
            "0009_rename_meeting_ses_mentor__73f9cd_idx_meeting_ses_mentor__62e580_idx_and_more",
        ),
        ("profiles", "0015_backfill_total_mentee_count_from_matches"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_id", models.CharField(max_length=128, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AGTE", "Automatically-Generated Timeline Event"),
                            ("MCTE", "Manually-Created Timeline Event"),
                            ("PrP", "Profile Post"),
                            ("CoP", "Community Post"),
                        ],
                        max_length=4,
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("community_id", models.UUIDField(blank=True, null=True)),
                ("show_on_profile", models.BooleanField(default=False)),
                ("content", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, null=True)),
                ("actor_role", models.CharField(blank=True, default="", max_length=16)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_timeline_events",
                        to="profiles.profile",
                    ),
                ),
                (
                    "mentorship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="mentorship.match",
                    ),
                ),
                (
                    "reposted_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reposts",
                        to="timeline.timelineevent",
                    ),
                ),
            ],
            options={
                "db_table": "timeline_events",
                "ordering": ["-timestamp", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["mentorship", "category", "is_deleted", "timestamp"],
                name="timeline_ev_mentors_bbea53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["author", "show_on_profile", "is_deleted", "timestamp"],
                name="timeline_ev_author__c5b65f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["category", "event_type", "timestamp"],
                name="timeline_ev_categor_885d8a_idx",
            ),
        ),
    ]
