# Generated by Django 6.0.3 on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineevent",
            name="media_url",
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
