# Generated by Django 6.0.3 on 2026-05-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0002_timelineevent_media_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineevent",
            name="media_url",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
