# Generated by Django 6.0.3 on 2026-04-02 19:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_skill_remove_profile_profiles_mentors_c5f0f6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=120),
                blank=True,
                default=list),
        ),
    ]
