# Generated by Django 6.0.3

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=3),
        ),
        migrations.AddField(
            model_name="profile",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
