# Generated by Django 5.x manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_average_rating_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileexpertise',
            name='expertise_field',
        ),
        migrations.RemoveField(
            model_name='profileexpertise',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expertise_fields',
        ),
        migrations.DeleteModel(
            name='ExpertiseField',
        ),
        migrations.DeleteModel(
            name='ProfileExpertise',
        ),
    ]
