# Generated by Django 6.0.3 on 2026-04-21 14:59

from django.conf import settings
from django.db import migrations, models


def sync_availability_slot_status(apps, schema_editor):
    """Sync status field with existing is_booked and MentorshipRequest data."""
    AvailabilitySlot = apps.get_model("profiles", "AvailabilitySlot")
    # Use apps.get_model to safely access mentorship app
    try:
        MentorshipRequest = apps.get_model("mentorship", "MentorshipRequest")
    except LookupError:
        # In case mentorship app is not yet available in the migration context
        return

    # Mark booked slots
    AvailabilitySlot.objects.filter(is_booked=True).update(status="BOOKED")

    # Mark slots with pending requests
    pending_slot_ids = MentorshipRequest.objects.filter(
        status="PENDING",
        slot__isnull=False
    ).values_list("slot_id", flat=True)
    
    AvailabilitySlot.objects.filter(
        id__in=pending_slot_ids, 
        status="AVAILABLE"
    ).update(status="PENDING")


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_expertise_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Ensure mentorship models are available
        ('mentorship', '0009_rename_meeting_ses_mentor__73f9cd_idx_meeting_ses_mentor__62e580_idx_and_more'), 
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=16),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['status', 'start_at'], name='availabilit_status_7417d2_idx'),
        ),
        migrations.RunPython(sync_availability_slot_status, reverse_code=migrations.RunPython.noop),
    ]
