# Generated by Django 6.0.3 on 2026-04-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_availabilityslot_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
    ]
