# Generated by Django 6.0.3 on 2026-04-24 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_profile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to='profiles.profile')),
            ],
            options={
                'db_table': 'community_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityTagMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_memberships', to='profiles.profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='profiles.communitytag')),
            ],
            options={
                'db_table': 'community_tag_memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='communitytag',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='community_tags', through='profiles.CommunityTagMembership', to='profiles.profile'),
        ),
        migrations.AddConstraint(
            model_name='communitytagmembership',
            constraint=models.UniqueConstraint(fields=('profile', 'tag'), name='uniq_membership_per_profile_tag'),
        ),
        migrations.AddIndex(
            model_name='communitytag',
            index=models.Index(fields=['slug'], name='community_t_slug_a15e33_idx'),
        ),
        migrations.AddIndex(
            model_name='communitytag',
            index=models.Index(fields=['-member_count', 'name'], name='community_t_member__99789b_idx'),
        ),
    ]
