# Generated by Django 6.0.3 on 2026-05-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_backfill_total_mentee_count_from_matches"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True,
                help_text="User-uploaded profile picture. Takes priority over picture_url.",
                null=True,
                upload_to="profile_pictures/%Y/%m/",
            ),
        ),
    ]
