# Generated by Django 6.0.3 on 2026-05-03 21:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitytag",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="share_precise_location",
            field=models.BooleanField(default=True),
        ),
    ]
