# Generated by Django 6.0.3 on 2026-05-07 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_communitytag_location_profile_share_precise_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profile",
            name="profiles_is_visi_66d764_idx",
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["show_initials_only"], name="profiles_show_in_6e21ba_idx"),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_visible",
        ),
    ]
