# Generated by Django 6.0.3 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_communitytag_location_profile_share_precise_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='availabilityslot',
            name='availabilit_is_book_7387a7_idx',
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='is_booked',
        ),
    ]
