# Generated by Django 6.0.3 on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_availabilityslot_is_booked'),
        ('profiles', '0018_remove_profile_profiles_is_visi_66d764_idx_and_more'),
    ]

    operations = [
    ]
