# Generated by Django 6.0.3 on 2026-05-07 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        ("profiles", "0019_merge_0018_conflicts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("delivered", "Delivered"), ("read", "Read")],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "message_read_receipts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="messagereport",
            name="uniq_message_report_per_reporter",
        ),
        migrations.AddField(
            model_name="readreceipt",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_receipts",
                to="messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="readreceipt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_read_receipts",
                to="profiles.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="readreceipt",
            unique_together={("message", "user")},
        ),
        migrations.DeleteModel(
            name="MessageReport",
        ),
    ]
