# Generated by Django 6.0.3 on 2026-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_readreceipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
